//! H.263 variable-length code tables, transcribed from ITU-T H.263 tables
//! 8, 13, 14 and 16 by way of `reference/h263-rs/h263/src/parser/`.
//!
//! Each table is a BINARY TREE flattened into an array: a `fork` holds the
//! index to jump to for a 0 bit and for a 1 bit, and every other variant is
//! a leaf. Decoding is a walk from index 0, one bit per fork. Generated —
//! do not hand-edit; see the transcription note in `h263.zig`.

pub const McbpcNode = union(enum) {
    fork: [2]u16,
    /// A stuffing code carries no macroblock; read another header.
    stuffing,
    invalid,
    valid: struct { kind: MbKind, cb: bool, cr: bool },
};

pub const MbKind = enum {
    intra,
    intraq,
    inter,
    interq,
    inter4v,
    inter4vq,

    pub fn isIntra(self: MbKind) bool {
        return self == .intra or self == .intraq;
    }

    pub fn isInter(self: MbKind) bool {
        return !self.isIntra();
    }

    pub fn hasQuant(self: MbKind) bool {
        return self == .intraq or self == .interq or self == .inter4vq;
    }

    pub fn hasFourVec(self: MbKind) bool {
        return self == .inter4v or self == .inter4vq;
    }
};

pub const CbpyNode = union(enum) {
    fork: [2]u16,
    invalid,
    valid: [4]bool,
};

pub const MvdNode = union(enum) {
    fork: [2]u16,
    invalid,
    /// The vector component, in HALF-pel units.
    halfpel: i16,
};

pub const TcoefNode = union(enum) {
    fork: [2]u16,
    invalid,
    /// A long-form coefficient follows in the bitstream.
    escape,
    run: struct { last: bool, run: u8, level: u8 },
};

pub const mcbpc_i_table = [_]McbpcNode{
    .{ .fork = .{ 2, 1 } },
    .{ .valid = .{ .kind = .intra, .cb = false, .cr = false } },
    .{ .fork = .{ 6, 3 } },
    .{ .fork = .{ 4, 5 } },
    .{ .valid = .{ .kind = .intra, .cb = true, .cr = false } },
    .{ .valid = .{ .kind = .intra, .cb = true, .cr = true } },
    .{ .fork = .{ 8, 7 } },
    .{ .valid = .{ .kind = .intra, .cb = false, .cr = true } },
    .{ .fork = .{ 10, 9 } },
    .{ .valid = .{ .kind = .intraq, .cb = false, .cr = false } },
    .{ .fork = .{ 14, 11 } },
    .{ .fork = .{ 12, 13 } },
    .{ .valid = .{ .kind = .intraq, .cb = true, .cr = false } },
    .{ .valid = .{ .kind = .intraq, .cb = true, .cr = true } },
    .{ .fork = .{ 16, 20 } },
    .invalid,
    .{ .fork = .{ 17, 15 } },
    .{ .fork = .{ 18, 15 } },
    .{ .fork = .{ 15, 19 } },
    .stuffing,
    .{ .valid = .{ .kind = .intraq, .cb = false, .cr = true } },
};

pub const mcbpc_p_table = [_]McbpcNode{
    .{ .fork = .{ 2, 1 } },
    .{ .valid = .{ .kind = .inter, .cb = false, .cr = false } },
    .{ .fork = .{ 6, 3 } },
    .{ .fork = .{ 4, 5 } },
    .{ .valid = .{ .kind = .inter4v, .cb = false, .cr = false } },
    .{ .valid = .{ .kind = .interq, .cb = false, .cr = false } },
    .{ .fork = .{ 10, 7 } },
    .{ .fork = .{ 8, 9 } },
    .{ .valid = .{ .kind = .inter, .cb = true, .cr = false } },
    .{ .valid = .{ .kind = .inter, .cb = false, .cr = true } },
    .{ .fork = .{ 16, 11 } },
    .{ .fork = .{ 13, 12 } },
    .{ .valid = .{ .kind = .intra, .cb = false, .cr = false } },
    .{ .fork = .{ 14, 15 } },
    .{ .valid = .{ .kind = .intraq, .cb = false, .cr = false } },
    .{ .valid = .{ .kind = .inter, .cb = true, .cr = true } },
    .{ .fork = .{ 24, 17 } },
    .{ .fork = .{ 18, 21 } },
    .{ .fork = .{ 19, 20 } },
    .{ .valid = .{ .kind = .inter4v, .cb = true, .cr = false } },
    .{ .valid = .{ .kind = .inter4v, .cb = false, .cr = true } },
    .{ .fork = .{ 22, 23 } },
    .{ .valid = .{ .kind = .interq, .cb = true, .cr = false } },
    .{ .valid = .{ .kind = .interq, .cb = false, .cr = true } },
    .{ .fork = .{ 30, 25 } },
    .{ .fork = .{ 27, 26 } },
    .{ .valid = .{ .kind = .intra, .cb = true, .cr = true } },
    .{ .fork = .{ 28, 29 } },
    .{ .valid = .{ .kind = .intra, .cb = false, .cr = true } },
    .{ .valid = .{ .kind = .inter4v, .cb = true, .cr = true } },
    .{ .fork = .{ 36, 31 } },
    .{ .fork = .{ 33, 32 } },
    .{ .valid = .{ .kind = .intra, .cb = true, .cr = false } },
    .{ .fork = .{ 34, 35 } },
    .{ .valid = .{ .kind = .intraq, .cb = false, .cr = true } },
    .{ .valid = .{ .kind = .interq, .cb = true, .cr = true } },
    .{ .fork = .{ 40, 37 } },
    .{ .fork = .{ 38, 39 } },
    .{ .valid = .{ .kind = .intraq, .cb = true, .cr = true } },
    .{ .valid = .{ .kind = .intraq, .cb = true, .cr = false } },
    .{ .fork = .{ 42, 41 } },
    .stuffing,
    .{ .fork = .{ 43, 44 } },
    .invalid,
    .{ .fork = .{ 45, 46 } },
    .{ .valid = .{ .kind = .inter4vq, .cb = false, .cr = false } },
    .{ .fork = .{ 47, 50 } },
    .{ .fork = .{ 48, 49 } },
    .{ .valid = .{ .kind = .inter4vq, .cb = false, .cr = true } },
    .invalid,
    .{ .fork = .{ 51, 52 } },
    .{ .valid = .{ .kind = .inter4vq, .cb = true, .cr = false } },
    .{ .valid = .{ .kind = .inter4vq, .cb = true, .cr = true } },
};

pub const cbpy_table = [_]CbpyNode{
    .{ .fork = .{ 1, 24 } },
    .{ .fork = .{ 2, 17 } },
    .{ .fork = .{ 3, 12 } },
    .{ .fork = .{ 4, 9 } },
    .{ .fork = .{ 5, 6 } },
    .invalid,
    .{ .fork = .{ 7, 8 } },
    .{ .valid = .{ false, true, true, false } },
    .{ .valid = .{ true, false, false, true } },
    .{ .fork = .{ 10, 11 } },
    .{ .valid = .{ true, false, false, false } },
    .{ .valid = .{ false, true, false, false } },
    .{ .fork = .{ 13, 16 } },
    .{ .fork = .{ 14, 15 } },
    .{ .valid = .{ false, false, true, false } },
    .{ .valid = .{ false, false, false, true } },
    .{ .valid = .{ false, false, false, false } },
    .{ .fork = .{ 18, 21 } },
    .{ .fork = .{ 19, 20 } },
    .{ .valid = .{ true, true, false, false } },
    .{ .valid = .{ true, false, true, false } },
    .{ .fork = .{ 22, 23 } },
    .{ .valid = .{ true, true, true, false } },
    .{ .valid = .{ false, true, false, true } },
    .{ .fork = .{ 25, 32 } },
    .{ .fork = .{ 26, 29 } },
    .{ .fork = .{ 27, 28 } },
    .{ .valid = .{ true, true, false, true } },
    .{ .valid = .{ false, false, true, true } },
    .{ .fork = .{ 30, 31 } },
    .{ .valid = .{ true, false, true, true } },
    .{ .valid = .{ false, true, true, true } },
    .{ .valid = .{ true, true, true, true } },
};

pub const mvd_table = [_]MvdNode{
    .{ .fork = .{ 2, 1 } },
    .{ .halfpel = 0 },
    .{ .fork = .{ 6, 3 } },
    .{ .fork = .{ 4, 5 } },
    .{ .halfpel = 1 },
    .{ .halfpel = -1 },
    .{ .fork = .{ 10, 7 } },
    .{ .fork = .{ 8, 9 } },
    .{ .halfpel = 2 },
    .{ .halfpel = -2 },
    .{ .fork = .{ 14, 11 } },
    .{ .fork = .{ 12, 13 } },
    .{ .halfpel = 3 },
    .{ .halfpel = -3 },
    .{ .fork = .{ 26, 15 } },
    .{ .fork = .{ 19, 16 } },
    .{ .fork = .{ 17, 18 } },
    .{ .halfpel = 4 },
    .{ .halfpel = -4 },
    .{ .fork = .{ 23, 20 } },
    .{ .fork = .{ 21, 22 } },
    .{ .halfpel = 5 },
    .{ .halfpel = -5 },
    .{ .fork = .{ 24, 25 } },
    .{ .halfpel = 6 },
    .{ .halfpel = -6 },
    .{ .fork = .{ 50, 27 } },
    .{ .fork = .{ 31, 28 } },
    .{ .fork = .{ 29, 30 } },
    .{ .halfpel = 7 },
    .{ .halfpel = -7 },
    .{ .fork = .{ 39, 32 } },
    .{ .fork = .{ 36, 33 } },
    .{ .fork = .{ 34, 35 } },
    .{ .halfpel = 8 },
    .{ .halfpel = -8 },
    .{ .fork = .{ 37, 38 } },
    .{ .halfpel = 9 },
    .{ .halfpel = -9 },
    .{ .fork = .{ 43, 40 } },
    .{ .fork = .{ 41, 42 } },
    .{ .halfpel = 10 },
    .{ .halfpel = -10 },
    .{ .fork = .{ 47, 44 } },
    .{ .fork = .{ 45, 46 } },
    .{ .halfpel = 11 },
    .{ .halfpel = -11 },
    .{ .fork = .{ 48, 49 } },
    .{ .halfpel = 12 },
    .{ .halfpel = -12 },
    .{ .fork = .{ 82, 51 } },
    .{ .fork = .{ 67, 52 } },
    .{ .fork = .{ 60, 53 } },
    .{ .fork = .{ 57, 54 } },
    .{ .fork = .{ 55, 56 } },
    .{ .halfpel = 13 },
    .{ .halfpel = -13 },
    .{ .fork = .{ 58, 59 } },
    .{ .halfpel = 14 },
    .{ .halfpel = -14 },
    .{ .fork = .{ 64, 61 } },
    .{ .fork = .{ 62, 63 } },
    .{ .halfpel = 15 },
    .{ .halfpel = -15 },
    .{ .fork = .{ 65, 66 } },
    .{ .halfpel = 16 },
    .{ .halfpel = -16 },
    .{ .fork = .{ 75, 68 } },
    .{ .fork = .{ 72, 69 } },
    .{ .fork = .{ 70, 71 } },
    .{ .halfpel = 17 },
    .{ .halfpel = -17 },
    .{ .fork = .{ 73, 74 } },
    .{ .halfpel = 18 },
    .{ .halfpel = -18 },
    .{ .fork = .{ 79, 76 } },
    .{ .fork = .{ 77, 78 } },
    .{ .halfpel = 19 },
    .{ .halfpel = -19 },
    .{ .fork = .{ 80, 81 } },
    .{ .halfpel = 20 },
    .{ .halfpel = -20 },
    .{ .fork = .{ 98, 83 } },
    .{ .fork = .{ 91, 84 } },
    .{ .fork = .{ 88, 85 } },
    .{ .fork = .{ 86, 87 } },
    .{ .halfpel = 21 },
    .{ .halfpel = -21 },
    .{ .fork = .{ 89, 90 } },
    .{ .halfpel = 22 },
    .{ .halfpel = -22 },
    .{ .fork = .{ 95, 92 } },
    .{ .fork = .{ 93, 94 } },
    .{ .halfpel = 23 },
    .{ .halfpel = -23 },
    .{ .fork = .{ 96, 97 } },
    .{ .halfpel = 24 },
    .{ .halfpel = -24 },
    .{ .fork = .{ 114, 99 } },
    .{ .fork = .{ 107, 100 } },
    .{ .fork = .{ 104, 101 } },
    .{ .fork = .{ 102, 103 } },
    .{ .halfpel = 25 },
    .{ .halfpel = -25 },
    .{ .fork = .{ 105, 106 } },
    .{ .halfpel = 26 },
    .{ .halfpel = -26 },
    .{ .fork = .{ 111, 108 } },
    .{ .fork = .{ 109, 110 } },
    .{ .halfpel = 27 },
    .{ .halfpel = -27 },
    .{ .fork = .{ 112, 113 } },
    .{ .halfpel = 28 },
    .{ .halfpel = -28 },
    .{ .fork = .{ 122, 115 } },
    .{ .fork = .{ 119, 116 } },
    .{ .fork = .{ 117, 118 } },
    .{ .halfpel = 29 },
    .{ .halfpel = -29 },
    .{ .fork = .{ 120, 121 } },
    .{ .halfpel = 30 },
    .{ .halfpel = -30 },
    .{ .fork = .{ 129, 123 } },
    .{ .fork = .{ 127, 124 } },
    .{ .fork = .{ 125, 126 } },
    .{ .halfpel = 31 },
    .{ .halfpel = -31 },
    .{ .fork = .{ 129, 128 } },
    .{ .halfpel = -32 },
    .invalid,
};

pub const tcoef_table = [_]TcoefNode{
    .{ .fork = .{ 8, 1 } },
    .{ .fork = .{ 2, 3 } },
    .{ .run = .{ .last = false, .run = 0, .level = 1 } },
    .{ .fork = .{ 4, 5 } },
    .{ .run = .{ .last = false, .run = 1, .level = 1 } },
    .{ .fork = .{ 6, 7 } },
    .{ .run = .{ .last = false, .run = 2, .level = 1 } },
    .{ .run = .{ .last = false, .run = 0, .level = 2 } },
    .{ .fork = .{ 28, 9 } },
    .{ .fork = .{ 15, 10 } },
    .{ .fork = .{ 12, 11 } },
    .{ .run = .{ .last = true, .run = 0, .level = 1 } },
    .{ .fork = .{ 13, 14 } },
    .{ .run = .{ .last = false, .run = 4, .level = 1 } },
    .{ .run = .{ .last = false, .run = 3, .level = 1 } },
    .{ .fork = .{ 16, 23 } },
    .{ .fork = .{ 17, 20 } },
    .{ .fork = .{ 18, 19 } },
    .{ .run = .{ .last = false, .run = 9, .level = 1 } },
    .{ .run = .{ .last = false, .run = 8, .level = 1 } },
    .{ .fork = .{ 21, 22 } },
    .{ .run = .{ .last = false, .run = 7, .level = 1 } },
    .{ .run = .{ .last = false, .run = 6, .level = 1 } },
    .{ .fork = .{ 25, 24 } },
    .{ .run = .{ .last = false, .run = 5, .level = 1 } },
    .{ .fork = .{ 26, 27 } },
    .{ .run = .{ .last = false, .run = 1, .level = 2 } },
    .{ .run = .{ .last = false, .run = 0, .level = 3 } },
    .{ .fork = .{ 52, 29 } },
    .{ .fork = .{ 37, 30 } },
    .{ .fork = .{ 31, 34 } },
    .{ .fork = .{ 32, 33 } },
    .{ .run = .{ .last = true, .run = 4, .level = 1 } },
    .{ .run = .{ .last = true, .run = 3, .level = 1 } },
    .{ .fork = .{ 35, 36 } },
    .{ .run = .{ .last = true, .run = 2, .level = 1 } },
    .{ .run = .{ .last = true, .run = 1, .level = 1 } },
    .{ .fork = .{ 38, 45 } },
    .{ .fork = .{ 39, 42 } },
    .{ .fork = .{ 40, 41 } },
    .{ .run = .{ .last = true, .run = 8, .level = 1 } },
    .{ .run = .{ .last = true, .run = 7, .level = 1 } },
    .{ .fork = .{ 43, 44 } },
    .{ .run = .{ .last = true, .run = 6, .level = 1 } },
    .{ .run = .{ .last = true, .run = 5, .level = 1 } },
    .{ .fork = .{ 46, 49 } },
    .{ .fork = .{ 47, 48 } },
    .{ .run = .{ .last = false, .run = 12, .level = 1 } },
    .{ .run = .{ .last = false, .run = 11, .level = 1 } },
    .{ .fork = .{ 50, 51 } },
    .{ .run = .{ .last = false, .run = 10, .level = 1 } },
    .{ .run = .{ .last = false, .run = 0, .level = 4 } },
    .{ .fork = .{ 90, 53 } },
    .{ .fork = .{ 69, 54 } },
    .{ .fork = .{ 55, 62 } },
    .{ .fork = .{ 56, 59 } },
    .{ .fork = .{ 57, 58 } },
    .{ .run = .{ .last = true, .run = 11, .level = 1 } },
    .{ .run = .{ .last = true, .run = 10, .level = 1 } },
    .{ .fork = .{ 60, 61 } },
    .{ .run = .{ .last = true, .run = 9, .level = 1 } },
    .{ .run = .{ .last = false, .run = 14, .level = 1 } },
    .{ .fork = .{ 63, 66 } },
    .{ .fork = .{ 64, 65 } },
    .{ .run = .{ .last = false, .run = 13, .level = 1 } },
    .{ .run = .{ .last = false, .run = 2, .level = 2 } },
    .{ .fork = .{ 67, 68 } },
    .{ .run = .{ .last = false, .run = 1, .level = 3 } },
    .{ .run = .{ .last = false, .run = 0, .level = 5 } },
    .{ .fork = .{ 77, 70 } },
    .{ .fork = .{ 71, 74 } },
    .{ .fork = .{ 72, 73 } },
    .{ .run = .{ .last = true, .run = 15, .level = 1 } },
    .{ .run = .{ .last = true, .run = 14, .level = 1 } },
    .{ .fork = .{ 75, 76 } },
    .{ .run = .{ .last = true, .run = 13, .level = 1 } },
    .{ .run = .{ .last = true, .run = 12, .level = 1 } },
    .{ .fork = .{ 78, 85 } },
    .{ .fork = .{ 79, 82 } },
    .{ .fork = .{ 80, 81 } },
    .{ .run = .{ .last = false, .run = 16, .level = 1 } },
    .{ .run = .{ .last = false, .run = 15, .level = 1 } },
    .{ .fork = .{ 83, 84 } },
    .{ .run = .{ .last = false, .run = 4, .level = 2 } },
    .{ .run = .{ .last = false, .run = 3, .level = 2 } },
    .{ .fork = .{ 86, 89 } },
    .{ .fork = .{ 87, 88 } },
    .{ .run = .{ .last = false, .run = 0, .level = 7 } },
    .{ .run = .{ .last = false, .run = 0, .level = 6 } },
    .{ .run = .{ .last = true, .run = 16, .level = 1 } },
    .{ .fork = .{ 124, 91 } },
    .{ .fork = .{ 92, 109 } },
    .{ .fork = .{ 93, 102 } },
    .{ .fork = .{ 94, 99 } },
    .{ .fork = .{ 95, 98 } },
    .{ .fork = .{ 96, 97 } },
    .{ .run = .{ .last = false, .run = 0, .level = 9 } },
    .{ .run = .{ .last = false, .run = 0, .level = 8 } },
    .{ .run = .{ .last = true, .run = 24, .level = 1 } },
    .{ .fork = .{ 100, 101 } },
    .{ .run = .{ .last = true, .run = 23, .level = 1 } },
    .{ .run = .{ .last = true, .run = 22, .level = 1 } },
    .{ .fork = .{ 103, 106 } },
    .{ .fork = .{ 104, 105 } },
    .{ .run = .{ .last = true, .run = 21, .level = 1 } },
    .{ .run = .{ .last = true, .run = 20, .level = 1 } },
    .{ .fork = .{ 107, 108 } },
    .{ .run = .{ .last = true, .run = 19, .level = 1 } },
    .{ .run = .{ .last = true, .run = 18, .level = 1 } },
    .{ .fork = .{ 110, 117 } },
    .{ .fork = .{ 111, 114 } },
    .{ .fork = .{ 112, 113 } },
    .{ .run = .{ .last = true, .run = 17, .level = 1 } },
    .{ .run = .{ .last = true, .run = 0, .level = 2 } },
    .{ .fork = .{ 115, 116 } },
    .{ .run = .{ .last = false, .run = 22, .level = 1 } },
    .{ .run = .{ .last = false, .run = 21, .level = 1 } },
    .{ .fork = .{ 118, 121 } },
    .{ .fork = .{ 119, 120 } },
    .{ .run = .{ .last = false, .run = 20, .level = 1 } },
    .{ .run = .{ .last = false, .run = 19, .level = 1 } },
    .{ .fork = .{ 122, 123 } },
    .{ .run = .{ .last = false, .run = 18, .level = 1 } },
    .{ .run = .{ .last = false, .run = 17, .level = 1 } },
    .{ .fork = .{ 174, 125 } },
    .{ .fork = .{ 127, 126 } },
    .escape,
    .{ .fork = .{ 128, 143 } },
    .{ .fork = .{ 129, 136 } },
    .{ .fork = .{ 130, 133 } },
    .{ .fork = .{ 131, 132 } },
    .{ .run = .{ .last = false, .run = 0, .level = 12 } },
    .{ .run = .{ .last = false, .run = 1, .level = 5 } },
    .{ .fork = .{ 134, 135 } },
    .{ .run = .{ .last = false, .run = 23, .level = 1 } },
    .{ .run = .{ .last = false, .run = 24, .level = 1 } },
    .{ .fork = .{ 137, 140 } },
    .{ .fork = .{ 138, 139 } },
    .{ .run = .{ .last = true, .run = 29, .level = 1 } },
    .{ .run = .{ .last = true, .run = 30, .level = 1 } },
    .{ .fork = .{ 141, 142 } },
    .{ .run = .{ .last = true, .run = 31, .level = 1 } },
    .{ .run = .{ .last = true, .run = 32, .level = 1 } },
    .{ .fork = .{ 144, 159 } },
    .{ .fork = .{ 145, 152 } },
    .{ .fork = .{ 146, 149 } },
    .{ .fork = .{ 147, 148 } },
    .{ .run = .{ .last = false, .run = 1, .level = 6 } },
    .{ .run = .{ .last = false, .run = 2, .level = 4 } },
    .{ .fork = .{ 150, 151 } },
    .{ .run = .{ .last = false, .run = 4, .level = 3 } },
    .{ .run = .{ .last = false, .run = 5, .level = 3 } },
    .{ .fork = .{ 153, 156 } },
    .{ .fork = .{ 154, 155 } },
    .{ .run = .{ .last = false, .run = 6, .level = 3 } },
    .{ .run = .{ .last = false, .run = 10, .level = 2 } },
    .{ .fork = .{ 157, 158 } },
    .{ .run = .{ .last = false, .run = 25, .level = 1 } },
    .{ .run = .{ .last = false, .run = 26, .level = 1 } },
    .{ .fork = .{ 160, 167 } },
    .{ .fork = .{ 161, 164 } },
    .{ .fork = .{ 162, 163 } },
    .{ .run = .{ .last = true, .run = 33, .level = 1 } },
    .{ .run = .{ .last = true, .run = 34, .level = 1 } },
    .{ .fork = .{ 165, 166 } },
    .{ .run = .{ .last = true, .run = 35, .level = 1 } },
    .{ .run = .{ .last = true, .run = 36, .level = 1 } },
    .{ .fork = .{ 168, 171 } },
    .{ .fork = .{ 169, 170 } },
    .{ .run = .{ .last = true, .run = 37, .level = 1 } },
    .{ .run = .{ .last = true, .run = 38, .level = 1 } },
    .{ .fork = .{ 172, 173 } },
    .{ .run = .{ .last = true, .run = 39, .level = 1 } },
    .{ .run = .{ .last = true, .run = 40, .level = 1 } },
    .{ .fork = .{ 190, 175 } },
    .{ .fork = .{ 176, 183 } },
    .{ .fork = .{ 177, 180 } },
    .{ .fork = .{ 178, 179 } },
    .{ .run = .{ .last = false, .run = 9, .level = 2 } },
    .{ .run = .{ .last = false, .run = 8, .level = 2 } },
    .{ .fork = .{ 181, 182 } },
    .{ .run = .{ .last = false, .run = 7, .level = 2 } },
    .{ .run = .{ .last = false, .run = 6, .level = 2 } },
    .{ .fork = .{ 184, 187 } },
    .{ .fork = .{ 185, 186 } },
    .{ .run = .{ .last = false, .run = 5, .level = 2 } },
    .{ .run = .{ .last = false, .run = 3, .level = 3 } },
    .{ .fork = .{ 188, 189 } },
    .{ .run = .{ .last = false, .run = 2, .level = 3 } },
    .{ .run = .{ .last = false, .run = 1, .level = 4 } },
    .{ .fork = .{ 198, 191 } },
    .{ .fork = .{ 192, 195 } },
    .{ .fork = .{ 193, 194 } },
    .{ .run = .{ .last = true, .run = 28, .level = 1 } },
    .{ .run = .{ .last = true, .run = 27, .level = 1 } },
    .{ .fork = .{ 196, 197 } },
    .{ .run = .{ .last = true, .run = 26, .level = 1 } },
    .{ .run = .{ .last = true, .run = 25, .level = 1 } },
    .{ .fork = .{ 206, 199 } },
    .{ .fork = .{ 200, 203 } },
    .{ .fork = .{ 201, 202 } },
    .{ .run = .{ .last = true, .run = 1, .level = 2 } },
    .{ .run = .{ .last = true, .run = 0, .level = 3 } },
    .{ .fork = .{ 204, 205 } },
    .{ .run = .{ .last = false, .run = 0, .level = 11 } },
    .{ .run = .{ .last = false, .run = 0, .level = 10 } },
    .invalid,
};
